@extends('layouts.app')

@push('styles')
<style>
    p {
        text-align: justify;
        text-justify: inter-word;
    }
</style>
@endpush

@section('content')
<main class="pt-90">
    <div class="mb-4 pb-4"></div>
    <section class="contact-us container">
        <div class="mw-930">
            <h2 class="page-title">Privacy Policy</h2>
        </div>

        <div class="about-us__content pb-5 mb-5">
            <div class="mw-930">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

                <h2>Interpretation and Definitions</h2>
                <h3>Interpretation</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper.</p>

                <h3>Definitions</h3>
                <ul>
                    <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                    <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                    <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to ABC Pvt. Ltd..</li>
                    <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                    <li><strong>Country</strong> refers to: India.</li>
                    <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                    <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                    <li><strong>Service</strong> refers to the Website.</li>
                    <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
                    <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                    <li><strong>Website</strong> refers to Laravel ECOM, accessible from this <a href="{{ route('home') }}">link</a>.</li>
                    <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                </ul>

                <h2>Collecting and Using Your Personal Data</h2>
                <h3>Types of Data Collected</h3>
                <h4>Personal Data</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra.</p>
                <ul>
                    <li>Email address</li>
                    <li>First name and last name</li>
                    <li>Phone number</li>
                    <li>Address, State, Province, ZIP/Postal code, City</li>
                    <li>Usage Data</li>
                </ul>

                <h4>Usage Data</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis. Ut felis.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augu, eu vulputate magna eros eu erat. Aliquam erat volutpat.</p>

                <h4>Tracking Technologies and Cookies</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam dui ligula, fringilla a, euismod sodales, sollicitudin vel, wisi. Nullam varius, turpis et commodo pharetra, est eros bibendum elit, nec luctus magna felis sit amet odio.</p>
                <ul>
                    <li><strong>Cookies or Browser Cookies.</strong> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</li>
                    <li><strong>Flash Cookies.</strong> Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. For more information, visit <a href="https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html" target="_blank">Adobe Help</a>.</li>
                    <li><strong>Web Beacons.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.</li>
                </ul>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sunt in culpa qui officia deserunt mollit anim id est laborum. You can learn more about cookies on <a href="https://www.privacypolicies.com/blog/cookies/" target="_blank">Privacy Policies website</a>.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ut eros at ligula dictum tincidunt. Aliquam erat volutpat.</p>
                <ul>
                    <li><strong>Necessary / Essential Cookies</strong><br>
                        Type: Session Cookies<br>
                        Administered by: Us<br>
                        Purpose: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce vel magna quis sem pulvinar facilisis.</li>
                    <li><strong>Cookies Policy / Notice Acceptance Cookies</strong><br>
                        Type: Persistent Cookies<br>
                        Administered by: Us<br>
                        Purpose: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam malesuada, nunc vel lacinia lacinia.</li>
                    <li><strong>Functionality Cookies</strong><br>
                        Type: Persistent Cookies<br>
                        Administered by: Us<br>
                        Purpose: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Velit nulla efficitur magna, vel scelerisque orci sapien nec erat.</li>
                </ul>

                <h3>Use of Your Personal Data</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sed nisi vitae ex ultricies egestas. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae.</p>
                <ul>
                    <li><strong>To provide and maintain our Service</strong>, Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li>
                    <li><strong>To manage Your Account:</strong> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec malesuada purus vitae dolor finibus.</li>
                    <li><strong>For the performance of a contract:</strong> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ac fermentum nunc ullamcorper.</li>
                    <li><strong>To contact You:</strong> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse potenti. In hac habitasse platea dictumst.</li>
                    <li><strong>To provide You with news</strong>, Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in ex vel justo ultricies gravida.</li>
                    <li><strong>To manage Your requests:</strong> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam at risus in felis scelerisque fringilla.</li>
                    <li><strong>For business transfers:</strong> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas id felis ut magna euismod efficitur.</li>
                    <li><strong>For other purposes</strong>: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vitae libero vitae nunc malesuada dignissim.</li>
                </ul>

                <h3>Sharing Your Personal Data</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vitae nisi vel ex facilisis efficitur. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
                <ul>
                    <li><strong>With Service Providers:</strong> Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li>
                    <li><strong>For business transfers:</strong> Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li>
                    <li><strong>With Affiliates:</strong> Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li>
                    <li><strong>With business partners:</strong> Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li>
                    <li><strong>With other users:</strong> Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li>
                    <li><strong>With Your consent</strong>: Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li>
                </ul>

                <h2>Retention of Your Personal Data</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ut eros at ligula dictum tincidunt. Aliquam erat volutpat. Fusce vel magna quis sem pulvinar facilisis.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam malesuada, nunc vel lacinia lacinia, velit nulla efficitur magna, vel scelerisque orci sapien nec erat. Proin sed nisi vitae ex ultricies egestas.</p>

                <h2>Transfer of Your Personal Data</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec malesuada purus vitae dolor finibus, ac fermentum nunc ullamcorper.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse potenti. In hac habitasse platea dictumst. Sed in ex vel justo ultricies gravida.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam at risus in felis scelerisque fringilla. Maecenas id felis ut magna euismod efficitur.</p>

                <h2>Delete Your Personal Data</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vitae libero vitae nunc malesuada dignissim. Cras vitae nisi vel ex facilisis efficitur.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>

                <h2>Disclosure of Your Personal Data</h2>
                <h3>Business Transactions</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi.</p>

                <h3>Law enforcement</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui.</p>

                <h3>Other legal requirements</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec non enim in turpis pulvinar facilisis. Ut felis.</p>
                <ul>
                    <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li>
                    <li>Praesent dapibus, neque id cursus faucibus, tortor neque egestas augu.</li>
                    <li>Eu vulputate magna eros eu erat. Aliquam erat volutpat.</li>
                    <li>Nam dui ligula, fringilla a, euismod sodales, sollicitudin vel, wisi.</li>
                    <li>Nullam varius, turpis et commodo pharetra, est eros bibendum elit.</li>
                </ul>

                <h2>Security of Your Personal Data</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nec luctus magna felis sit amet odio. Mauris vel erat vitae eros dictum elementum. Sed pretium.</p>

                <h2>Children's Privacy</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vel lacinia lacinia, velit nulla efficitur magna, vel scelerisque orci sapien nec erat. Proin sed nisi vitae ex ultricies egestas.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae.</p>

                <h2>Links to Other Websites</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec malesuada purus vitae dolor finibus, ac fermentum nunc ullamcorper.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse potenti. In hac habitasse platea dictumst.</p>

                <h2>Changes to this Privacy Policy</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in ex vel justo ultricies gravida. Nullam at risus in felis scelerisque fringilla.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas id felis ut magna euismod efficitur. Mauris vitae libero vitae nunc malesuada dignissim.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vitae nisi vel ex facilisis efficitur. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>

                <h2>Contact Us</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper.</p>
                <ul>
                    <li>By email: <a class="menu-link menu-link_us-s" href="mailto:privacy@example.com" target="_blank">privacy@example.com</a></li>
                    <li>By visiting this <a class="menu-link menu-link_us-s" href="{{ route('privacy_policy') }}">link</a> on our website.</li>
                </ul>
            </div>
        </div>
    </section>
</main>
@endsection

@push('scripts')

@endpush
